### ISSUE TITLE
SUPEE-6285

### ISSUE THREAD

**Issue by razbakov** [firegento/magento-ce#10]
add patch for:
- 1.9.1.1
- 1.9.1.0
- 1.9.0.0
- 1.8.1.0
- 1.7.0.2

**Comment by avoelkl** [comment]
In progress.

**Comment by avoelkl** [comment]
Current status:
- 1.9.1.1: done
- 1.9.1.0: done, SUPEE-6285 + previous SUPEE-5994
- 1.9.0.1: done SUPEE-6285 + previous SUPEE-5994, SUPEE-5344, SUPEE-1533

to do:
- 1.9.0.0
- 1.8.1.0
- 1.7.0.2

**Comment by SchumacherFM** [comment]
Thank you anna for doing this :-) :+1:

**Comment by razbakov** [comment]
**Done:**
- 1.8.1.0
- 1.9.0.0

**To Do:**
- 1.7.0.2

**Comment by razbakov** [comment]
1.7.0.2 will be done in https://github.com/firegento/magento/issues/31
