### ISSUE TITLE
Should composer installers be included in magento?

### ISSUE THREAD

**Issue by razbakov** [firegento/magento-ce#17]
I am not sure if we need to include this piece of code to composer, but it will make it easier to use composer to install magento, so end-users don't need to include it in their project composer json:

```
     "repositories": [
        {"type": "git", "url": "https://github.com/AydinHassan/magento-core-composer-installer"}
    ],
    "require": {
        "magento-hackathon/magento-composer-installer": "*",
        "aydin-hassan/magento-core-composer-installer": "*"
    },
```

**Comment by SchumacherFM** [comment]
ok

**Comment by therouv** [comment]
I'd vote against it, because there are way more composer installers out there, so the end-user should decide for themselves.

However, we could add a section to the README to list preferred Magento composer installers.

**Comment by razbakov** [comment]
ok, agree

**Comment by Flyingmana** [comment]
:-1: 

suggest is ok, but not require
