### ISSUE TITLE
Tag naming conventions

### ISSUE THREAD

**Issue by razbakov** [firegento/magento-ce#18]
@SchumacherFM hi! I wanted to discuss with you some tag naming conventions.

1) Most of composer modules I've seen are using tags without "v" prefix.
Can we agree on using version tags without prefix?

2) Signing tags with PGP keys is some unneeded overhead, that will just stop community from taking part in updates. Let's simplify the process?

3) Maybe it make sense to include descriptive changelog (like you did in README) in releases page: https://github.com/firegento/magento/releases. See for example 1.9.2.1

**Comment by SchumacherFM** [comment]
1. ok but old tags cannot be renamed because I know at least one who is using them
2. ok but it must be then an annotated tag
3. Sure!
