### ISSUE TITLE
1.9.2.1 not installing for me

### ISSUE THREAD

**Issue by dvdsndr** [firegento/magento-ce#19]
Updating dependencies (including require-dev)               
- MagentoCoreInstaller: Removing: "firegento/magento" version: "1.9.2.0" from: "/var/www/src"
- Removing firegento/magento (1.9.2.0)
- Installing firegento/magento (v1.9.2.1)
  Loading from cache
- MagentoCoreInstaller: Installing: "firegento/magento" version: "1.9.2.1" to: "/var/www/src"
  Writing lock file
  Generating autoload files
  /var/www/src/app/Mage.php is not a file.

**Comment by razbakov** [comment]
what is your composer.json?
try to follow this instructions: http://razbakov.com/blog/install-magento-via-composer/

**Comment by dvdsndr** [comment]
Ok that instruction worked for me. I was using a much more simplified composer.json like this. It did work for 1.9.2.0 but not for 1.9.2.1

{
    "require": {
        "magento-hackathon/magento-composer-installer": "2.1.1",
        "firegento/magento":                            "1.9.2.0"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/firegento/magento"
        },
        {
            "type": "vcs",
            "url": "https://github.com/mercator/magento-composer-installer"
        }
    ],
    "extra": {
        "magento-root-dir": ".",
        "magento-deploystrategy": "symlink",
        "magento-force": true
    }
}
