### ISSUE TITLE
Give it a try

### ISSUE THREAD

**Issue by razbakov** [firegento/magento-ce#27]
Let's give it a try to use one central repo for Magento: 
Firegento Magento Community Magento-1.x Mirror Github Repository with Patches.

Follow instructions in [README](https://github.com/firegento/magento) to install magento.
In case of any problems we will fix it ASAP.

Nowadays there are thousands of other magento-mirror-repos which are doing the same job every time when new patch or magento version is released. Here is just a small list of repos, which I know:
- [OpenMage/magento-lts](https://github.com/OpenMage/magento-lts)
- [bragento/magento-core](https://github.com/bragento/magento-core)
- [OpenMage/magento-mirror](https://github.com/OpenMage/magento-mirror/)
- [AydinHassan/magento-community](https://github.com/AydinHassan/magento-community)
- [WeareJH/magento-ce](https://github.com/WeareJH/magento-ce)

What if we bring our hands together and help each other to deliver security patches faster and with better quality?

**Comment by razbakov** [comment]
@LeeSaferite @tmotyl @manish172 @davidwindell @sebastianwagner @drobinson @kalenjordan @sunel @empiricompany @rafaelstz @AydinHassan @emateu @t-richards @ToonSpin @sebastianwagner @bragento @davidverholen @zifius @km-digitalpatrioten @daniel-rose @navarr @egon0 @flancer64 @adrien-louis-r

**Comment by davidwindell** [comment]
I wonder if https://github.com/magento would consider providing an official mirror alongside the old SVN repo (especially considering the recent security attacks).

**Comment by davidverholen** [comment]
Hey,
basically a very good idea. My first remark would be, that the branches should be composer compliant like in https://github.com/bragento/magento-core.

This leads to automatically generated dev - Versions pointing to each branch

**Comment by razbakov** [comment]
@davidwindell no, they don't have resources to manage it, but it would be really nice.
Maybe @benmarks can comment this.

@davidverholen we can do this, I created #29 for it

**Comment by tmotyl** [comment]
Good idea, and this is why the OpenMage/magento-lts was created. 
I'm in favor of using OpenMage as a central repo, as it's not bound to any company. Also @benmarks is a member of OpenMage, so it seems it's already on the radar of Magento inc.

I would be really happy if Magento would take the pull requests we;re creating and incorporate them into the official version. Maybe @piotrekkaminski knows if this is something Magento has in plans?

**Comment by razbakov** [comment]
@tmotyl Firegento not bound to any company as well. It is association with a lot of active members, that organises a lot of hackathons in Germany. @benmarks is active member of those hackathons.

OpenMage/magento-lts:
I see that there are branches corresponding to magento versions, but last release tag is 1.9.1.1.
I find a way how we apply patches in this repo is more composer-friendly and you can specify in composer.json:

```
"firegento/magento": "~1.9"
```

And each time you want update your magento you just need to run `composer update` without even changing `composer.json`

As for bugfixes I would recommend to have separate repo which could be used as magento-module and installed on top of magento. Thanks @SchumacherFM for this idea.

**Comment by kalenjordan** [comment]
Thanks @razbakov - will check this out next time I'm in security patch mode :)

**Comment by drobinson** [comment]
@razbakov LTS doesn't have the releases because each release from Magento gets a new branch - so definitions in composer.json like yours work exactly the same. But I agree...it would be great to have a central repo for community to agree on.

**Comment by LeeSaferite** [comment]
That was the whole idea behind OpenMage in the first place.

I'm always open to help there.

**Comment by sunel** [comment]
Sounds greate to me :thumbsup:

As i know `firegento/magento`  accepts only official patches , but `OpenMage/magento-lts`  accpets communtity patches which is great as magento core has many know bugs which are still not fixed for months .

If this central repo idea could incorporate both offical and community fixes it would be great.

**Comment by Flyingmana** [comment]
I also vote for contributing to OpenMage instead of doing it as part of Firegento. And I mean for a Magento Mirror, *_and_ for a fork which allows contributions.

Firegento is a partially good known community brand (at least in the german speaking area).
And, they may have a big number of members, but they lack of transparency of decisions and responsibilities.
Also, I dont trust their review workflow for such a core component

**Comment by davidverholen** [comment]
The openmage package seems broken on packagist.org. There is only one stable version (1.9.1.1) shown.

https://packagist.org/packages/openmage/magento-lts

Also we need a new version (or patch version) every time a new Patch is released, so magento is updated automatically for every customer.

Another Problem is, that it requires the magento composer installer directly. You can only use this package (except you replace the installer in every project) if you are using the hackathon installer. Not everyone does this.

Apart from this, it is unnecessary to require the installer in a core package since it does not  support core install anymore.

**Comment by Flyingmana** [comment]
as the primary problem is the composer installer
we created an Issue for it now (please, if you have an issue, create an Issue)

https://github.com/OpenMage/magento-lts/issues/554
