### ISSUE TITLE
Use "firegento/magento" as composer name

### ISSUE THREAD

**Issue by razbakov** [firegento/magento-ce#4]
Now it is for example "magento/1.9.1.0", which is not right.
It is better when composer name shows github organization and repo.

**Comment by SchumacherFM** [comment]
sure

**Comment by SchumacherFM** [comment]
There is no composer involved or what do you mean?

**Comment by razbakov** [comment]
composer.json now:

```
{
    "name": "magento/1.7.0.2",
    "license": "OSL-3.0",
    "description": "Magento CE",
    "homepage": "https://github.com/Zookal/magento-ce/tree/magento-1.7.0.2"
}
```

I suggest to change to:

```
{
    "name": "firegento/magento",
    "license": "OSL-3.0",
    "description": "Magento CE"
}
```

**Comment by therouv** [comment]
License should be:

```
{
    "name": "firegento/magento",
    "license": ["OSL-3.0", "AFL-3.0"],
    "description": "Magento CE"
}
```

But otherwise: :+1:

**Comment by SchumacherFM** [comment]
D'oh! Should have read the source of the branches 8-)

I'm not in the mood to change every branch to the new composer.json format

**Comment by razbakov** [comment]
i will do it

**Comment by razbakov** [comment]
@SchumacherFM 
I followed instructions in README and it is not possible to install it.
I suggest to use this way - https://github.com/kirchbergerknorr/magento/wiki

**Comment by razbakov** [comment]
and i would write README with working example

**Comment by razbakov** [comment]
you can test it now:

1) create composer.json with this content:

```
{
    "repositories": {
        "magento": {"type":"git", "url":"https://github.com/firegento/magento"},
        "firegento": {
            "type": "composer",
            "url": "http://packages.firegento.com"
        }
    },
    "require": {
        "firegento/magento": "1.9.2.0"
    },
    "extra": {
        "magento-root-dir": "src",
        "auto-append-gitignore": true,
        "magento-deploystrategy": "copy",
        "magento-force": true
    }
}
```

2) create `src` folder
3) run `composer update`

**Comment by razbakov** [comment]
**TODO**: update readme

**Comment by razbakov** [comment]
@SchumacherFM i fixed composer.json on magento-1.9.0.1 branch. What should we do with tag v1.9.0.1? Should we create new tag or force-fix this one?

**Comment by SchumacherFM** [comment]
force fix :-)
