### ISSUE TITLE
Add Magento 1.9.3.1

### ISSUE THREAD

**Issue by amansilla** [firegento/magento-ce#47]
Today was released a new version for Magento CE (1.9.3.1), I'd like to create a PR to solve this but as far as I know first a new branch "magento-1.9.3.1" should be first added to this repo. Anyone willing to do this?

**Comment by razbakov** [comment]
Thank you @amansilla! I created new branch magento-1.9.3.1

**Comment by razbakov** [comment]
added magento 1.9.3.1 in 93562d3984380a76ba98ab4dee1ff2e51ec37b52

**Comment by amansilla** [comment]
thanks for your work @razbakov
