### ISSUE TITLE
Update replacing original composer.json file

### ISSUE THREAD

**Issue by mozgbrasil** [firegento/magento-ce#51]
======
en_US
======

Hello

Good morning my friends

A few months ago I followed the following tutorial

Https://mozg.com.br/magento1/instalando-magento1

Where at the time was the installation of Magento 1.9.3.0

We can see in

https://mozg.com.br/magento1/instalando-magento1

If I come to update the project via composer

Running the command

	composer update

It notifies you of the new version of Magento 1.9.3.1

Magento update is done, but there is a problem

After the execution of the processes by the composer

Then I see that the file

composer.json is replaced by the following content

	{
	    "name": "firegento/magento",
	    "type": "magento-core",
	    "license": ["OSL-3.0", "AFL-3.0"],
	    "description": "Magento CE"
	}

AND

If I come to update the project via composer

Running the command

	composer update

Removal of modules that were already installed is done

I need help to stop this error

Do you know anything that might help me?

======
pt_BR
======

Ola 

Bom dia meus amigos

Em alguns meses atrás eu segui o seguinte tutorial 

https://mozg.com.br/magento1/instalando-magento1

Onde na ocasião foi feito a instalação do Magento 1.9.3.0

Podemos ver em

http://loja.cerebrum.com.br/composer.json

Caso eu venha a atualizar o projeto via composer

Executando o comando

	composer update

É informado sobre a nova versão do Magento 1.9.3.1

É feito a atualização do Magento, mas ocorre um problema

Após a execução dos processos pelo composer

Em seguida vejo que o arquivo

composer.json é substituido pelo seguinte conteudo

	{
	    "name": "firegento/magento",
	    "type": "magento-core",
	    "license": ["OSL-3.0", "AFL-3.0"],
	    "description": "Magento CE"
	}

E

Caso eu venha a atualizar o projeto via composer

Executando o comando

	composer update

É feito a remoção dos módulos que já estava instalado

Preciso de ajuda para não ocorrer mais esse erro

Sabem de algo que possa me ajudar ?

**Comment by jwohlfeil** [comment]
You could move all composer files and data to a subdirectory like that: http://take.ms/pRRMh

Then just change the deployment path to '../' like that:

`{
    "minimum-stability": "dev",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.firegento.com"
        }
    ],
    "extra": {
        "magento-root-dir": "../",
        "magento-deploystrategy": "copy",
        "magento-force": true
    },
    "require": {
        "aschroder/smtp_pro": "^2.0",
        "avstudnitz/fast-simple-import": "^0.7.0",
        "tim-reynolds/magento-qconfig": "^1.0",
        "avstudnitz/scopehint": "^0.6.0",
        "magento-hackathon/e-mail-preview": "^1.0",
        "connect20/debitpayment": "^1.1"
    }
}
`

Hope it helps, Jan

**Comment by mozgbrasil** [comment]
Thanks for interacting

This way it becomes rather strange, since most projects have the vendor folder at the root of the Magento project

And only in this case of composer-installed project use should I make this change, it does not become a common standard

I think the best solution would be to delete the composer.json file in the following repository

https://github.com/firegento/magento/blob/magento-1.9.3.1/composer.json

Or not allow file replacement if possible

**Comment by razbakov** [comment]
Here are additional properties for composer.json:

```
"extra": {
      "magento-root-dir": "src",
      "auto-append-gitignore": true,
      "magento-deploystrategy": "symlink",
      "magento-force": true
    }
```

`magento-root-dir` - configure your magento root dir, the directory where your magento resides. see [magento-composer-installer](https://github.com/Cotya/magento-composer-installer) for reference.

In my projects I have folder `src` as magento root dir, so I place my `composer.json` in project root and ignore `src` folder.

**Comment by razbakov** [comment]
> I think the best solution would be to delete the composer.json file in the following repository
> Or not allow file replacement if possible

That won't work, cuz composer requires composer.json in the repo.
