### ISSUE TITLE
Error Creating an Object

### ISSUE THREAD

**Issue by fullStackDataSolutions** [firegento/magento-ce#54]
Hello, 

I'm not sure if this is the correctly place to post this, if not please direct me to a proper location. I'm working on a website that is using Magento 1.8 and the URL is: [www.xb2h.com](https://www.xb2h.com)

I am receiving the following error in the system.log: 

`2017-01-25T04:48:28+00:00 ERR (3): Warning: Creating default object from empty value  in /chroot/home/crossing/xb2h.com/html/app/code/community/Nextend/AccordionMenu/library/accordionmenu/magento/tree.php on line 47`

I tried initializing a class, but that just created more errors.

**Comment by razbakov** [comment]
Hello @blazestudios23 

Magento related questions you can ask in [Magento Stack Exchange](http://magento.stackexchange.com/). 

But your question is about module integration, so ask an author of your module or hire magento developer.
