### ISSUE TITLE
Magento Ver 1.9.3.4 with new SUPEE-9767 v2

### ISSUE THREAD

**Issue by schrenkb1** [firegento/magento-ce#65]

**Comment by sickdaflip** [comment]
push

**Comment by codephunk** [comment]
push

**Comment by mrmoonlv** [comment]
push

**Comment by wytzejan** [comment]
push

**Comment by nolafs** [comment]
push, please

**Comment by popovserhii** [comment]
I've found alternative for this repository, it's https://github.com/bragento/magento-core.
- replace in your *composer.json*
"firegento/magento" : "1.9.3.*", -> "magento/core" : "1.9.3.4",
- run `composer update`

**Comment by razbakov** [comment]
Fixed. Please check
