### ISSUE TITLE
Release version for Magento 1.9.3.4

### ISSUE THREAD

**Issue by RiftLurker** [firegento/magento-ce#68]
It seems like [1.9.3.4 got merged into the magento-1.9.3.3 branch](https://github.com/firegento/magento/commit/92379f63ad7d5c2d4030a82e66d1cb89866a5c23) just like the [SUPEE-9767 patch](https://github.com/firegento/magento/commit/ce501f51ee435a3ec07cbec289e1a1af832fb766).
Can we get a release tag and maybe a separat branch for it?

**Comment by danslo** [comment]
Tagging @razbakov as he seems to have rights on this repository. Would be nice to have a 1.9.3.4 tag.

**Comment by razbakov** [comment]
Can you prepare PR please?

**Comment by danslo** [comment]
I don't have permissions to create branches here.

It will require something like

```bash
$ git checkout magento-1.9.3.3
$ git branch magento-1.9.3.4
$ git revert a1f2d77528e5f11d7268093f47ff512be96f3bc5
```

Then probably both branches need to be retagged (and force pushed). Which I can't do either.

**Comment by razbakov** [comment]
Please also see #69

**Comment by razbakov** [comment]
Also see #67

**Comment by razbakov** [comment]
@PostCrafter @danslo 
Fixed. Please check
