### ISSUE TITLE
New maintainer wanted!

### ISSUE THREAD

**Issue by razbakov** [firegento/magento-ce#69]
I am no more working with Magento and therefor I am looking for a new maintainer for this repository.

Does anyone want to volunteer?

**Comment by SchumacherFM** [comment]
Me neither

**Comment by danslo** [comment]
Since Magento 1.x isn't releasing that many versions, I'm open to maintaining this repo.

**Comment by razbakov** [comment]
@danslo you already have permission, right?

**Comment by razbakov** [comment]
@danslo can you please take care of open pull requests and issues?

**Comment by danslo** [comment]
Doesn't look like I have permissions to close / merge / etc.

**Comment by mautz-et-tong** [comment]
I will remove @razbakov and @SchumacherFM and add @danslo

**Comment by razbakov** [comment]
Great! Thanks!

**Comment by danslo** [comment]
Looks like it's sorted, thanks!
